### ISSUE TITLE
feat: redux (@stencil/redux deprecated)

### ISSUE THREAD

**Issue by miqmago** [ionic-team/stencil-store#151]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-store/issues) that already include this feature request, without success.

### Describe the Feature Request

Up to now I have been successfully using [@stencil/redux](https://www.npmjs.com/package/@stencil/redux).

I was updating some dependencies and I have seen that it has been deprecated. Please could you indicate if @stencil/store intention is to be a replacement for redux?

I'm not really sure if @stencil/store is the replacement so we can forget about reducers, actions and so on, and make complex things easy as it seems @stencil/store. I have some apps where the store is quite complex, containing even class objects with their methods so they are shared to the hole app, like a kind of singletons.

### Describe the Use Case

replacement of @stencil/redux

### Describe Alternatives

I have tried to integrate redux-toolkit without success, I haven't found any specific guide or example for stencil...

**Comment by miqmago** [comment]
@rwaskiewicz understood, many thanks.

Not sure if it's off-topic here and where to ask this question in this case: Currently, at our company, we have fully developend some big applications with stencil + ionic, even mobile apps with capacitor. They are well organized, blazing fast, with minimal boilerplate and really easy to maintain, but from your comment I'm wondering if this is a good strategy... Does it mean that stencil will not be the best option (or even an option) to develop full applications in near future? Is there any webinar talking about future plans?

Also is there anything we can do to help/support stencil to not leave full app development? When one starts programming in stencil, has the feeling that is reaching heaven in terms of freedom: the fact that it has no framework behind is amazing. One can feel that you is almost touching the heart of the navigator... :)

**Comment by rwaskiewicz** [comment]
Hey @miqmago,

That's great! We see Stencil as a piece of the application development workflow - it's a great place to build the web components for a shared library, a design system, etc. It's one that takes an active part in the Ionic Framework still and we plan for it to continue that way.

However, the Stencil redux package had not been worked on for 2 years. Rather than let it sit and receive no updates, we felt it more appropriate to signal now that we don't plan to develop the project further. Rather than try to "do it all", we'd rather focus on making Stencil the best web component compiler it can be.

> Also is there anything we can do to help/support stencil to not leave full app development? When one starts programming in stencil, has the feeling that is reaching heaven in terms of freedom: the fact that it has no framework behind is amazing. One can feel that you is almost touching the heart of the navigator... :)

❤️ We have a [Stencil Community](https://github.com/stencil-community) that folks are welcome to come and [propose new packages for](https://github.com/stencil-community/proposals). It is a GItHub organization where members of the the community build and maintain packages for Stencil that are not maintained by Ionic. There are a few packages that relate to application development if you're interested in getting involved!

**Comment by JohnMica** [comment]
hi there

its interesting that Stencil is going to still be supported into the future.

I do have  a few strange questions (I inherited a really old project written in Stencil that creates an SDK / web-components) 

- since the `@stencil/redux` is deprecated what options are to use for a state management where a 'theme' is updated independently by different users?
- `@stencil/store` feels like a really dumb down version of a state manager and I am not sure if its the right way to go about?
- any ideas on how I could approach this particular huge issue for me ?

I do not know React, Redux, etc...  so some advice would be greatly appreciated
